carts/urls.py
from django.conf.urls import url, include
from .views import *

# ^起始字符一定要加,$结束符号根据要求
urlpatterns = [
    url(r'^cart/$', cart, name='cart'),
    url(r'^add_goods/$', add_goods, name='add_goods'),
    url(r'^edit_goods_num/$', edit_goods_num, name='edit_goods_num'),
    url(r'^del_goods/$', del_goods, name='del_goods'),
]

goods/urls.py
from django.conf.urls import url, include
from .views import *

# ^起始字符一定要加,$结束符号根据要求
urlpatterns = [
    url(r'^index/$', index, name='index'),
    url(r'^detail/$', detail, name='detail'),
    url(r'^goods_list/(\d+)/(\d+)/$', goods_list, name='goods_list'),
]

myweb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', ''),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^order/', include('order.urls', namespace='order')),
    #url(r'^favicon.ico$', RedirectView.as_view(url='static/favicon.ico'))
]



#handler404 = 'my_app.views.my_custom_page_not_found_view'
#handler500 = 'my_app.views.my_custom_error_view'
#handler403 = 'my_app.views.my_custom_permission_denied_view'

carts/models.py
from django.db import models
from db.AbstractModel import *

# 购物车管理器
class CartManager(models.Manager):
    pass

# Create your models here.
class Cart(AbstractModel):
    # 购买商品
    cart_goods = models.ForeignKey('goods.GoodsInfo')
    # 购买数量
    cart_amount = models.IntegerField()
    # 所属用户
    cart_user = models.ForeignKey('users.User')

    objects = CartManager()










'''
# 自定义管理器模式
class 自定义管理器类名(models.Manager):
    # 管理器新增方法
    def 方法名(self):
        # 获取父类方法
        变量 = super(自定义管理器类名, self).all()
        """""""
        # 处理过程
        """"""" 
        return 变量
'''
'''
# 字段元选项
class Meta:
        # 重定义数据库的数据表名
        db_table = 'my_custom_dbname'
        # 表示该模型类为抽象类,不生成表
        abstract = True
        # 排序
        ordering = ['-id']
'''

goods/models.py
from django.db import models
from db.AbstractModel import *
from tinymce.models import HTMLField
# Create your models here.

# 分类模型
class Category(AbstractModel):

    # 产品分类名称
    cag_name = models.CharField(max_length=30)


# 商品信息管理类
class GoodsInfoManager(models.Manager):
    # 获得最新添加商品
    def get_new_goods(self, cag, num=4):
        return self.filter(goods_cag=cag).order_by('-id')[:num]

    def get_hot_goods(self, cag, num=3):
        return self.filter(goods_cag=cag).order_by('-good_visits')[:num]

    # 获得所有商品中最新的两个商品
    def get_new_by_all_goods(self, num=2):
        return self.all().order_by('-id')[:num]

    # 根据商品的id分类获取商品列表
    # def get_goods_by_cagid(self, cag_id):
    #     return self.filter(goods_cag_id=cag_id)

    # 根据商品分类的id获取商品列表
    def get_goods_by_cagid(self, cag_id, show):
        if show == 'price':
            return self.filter(goods_cag_id=cag_id).order_by('-good_price')

        if show == 'hot':
            return self.filter(goods_cag_id=cag_id).order_by('-good_visits')

        return self.filter(goods_cag_id=cag_id)

class GoodsInfo(AbstractModel):
    # 商品名称
    good_name = models.CharField(max_length=30)
    # 商品价格
    good_price = models.DecimalField(max_digits=10, decimal_places=2)
    # 商品图片(配置静态文件图片路径)
    good_image = models.ImageField()
    # 商品简述
    good_compendium = models.CharField(max_length=100)
    # 商品详情(配置富文本编辑器)
    good_details = HTMLField()
    # 商品上架
    good_status = models.BooleanField(default=True)
    # 商品单位
    good_unit = models.CharField(max_length=20)
    # 商品访问量
    good_visits = models.IntegerField(default=0)
    # 商品销量
    good_sales = models.IntegerField(default=0)
    # 商品分类
    goods_cag = models.ForeignKey(Category)

    objects = GoodsInfoManager()

# 广告模型
class Advertise(AbstractModel):
    # 广告名字
    ad_name = models.CharField(max_length=30)
    # 广告图片
    ad_image = models.ImageField(upload_to='ad')
    # 广告链接
    ad_link = models.CharField(max_length=100)








'''
# 自定义管理器模式
class 自定义管理器类名(models.Manager):
    # 管理器新增方法
    def 方法名(self):
        # 获取父类方法
        变量 = super(自定义管理器类名, self).all()
        """""""
        # 处理过程
        """"""" 
        return 变量
'''
'''
# 字段元选项
class Meta:
        # 重定义数据库的数据表名
        db_table = 'my_custom_dbname'
        # 表示该模型类为抽象类,不生成表
        abstract = True
        # 排序
        ordering = ['-id']
'''

carts/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from utils.wrappers import *
from .models import *
from django.http import JsonResponse
# Create your views here.


# 购物车
@check_permission #检查账户是否登录
def cart(request):
    # 取出购物车数据
    carts = Cart.objects.filter(cart_user_id=get_session(request, 'uid'))
    # 记录总数量和总价格
    total_num = 0
    total_money = 0
    # 遍历购物车统计
    for cart1 in carts:
        cart1.total_money = cart1.cart_amount * cart1.cart_goods.good_price
        total_money += cart1.total_money
        total_num += cart1.cart_amount
    # 加入carts中
    carts.total_money = total_money
    carts.total_num = total_num

    return render(request, 'carts/cart.html', locals())


# 商品添加到购物车
def add_goods(request):
    # 1.获取用户id,商品id,商品数量
    goods_id = get_getvalue(request, 'goods_id')
    user_id = get_session(request, 'uid')
    goods_num = get_getvalue(request, 'goods_num')
    print(goods_id, user_id)
    # 2.先判断是否在购物车中存在
    try:
        # 2.1如果存在,之更新商品的数量
        goods = Cart.objects.get(cart_user_id=user_id, cart_goods_id=goods_id)
        # 获得的goods_num是字符串,必须int
        goods.cart_amount += int(goods_num)
        goods.save()
    except Exception as error:
        # 2.2如果不存在,新增一条购物车的商品数据
        # print(error)
        goods = Cart()
        goods.cart_goods_id = goods_id
        goods.cart_user_id = user_id
        goods.cart_amount = goods_num
        goods.save()
    finally:
        # 将当前购物车商品数量总和返回
        total = 0
        carts = Cart.objects.filter(cart_user_id=user_id)
        for good in carts:
            total += good.cart_amount

    return JsonResponse({'total': total})


def edit_goods_num(request):
    # 获取商品id
    goods_id = get_getvalue(request, 'goods_id')
    # 获取商品数量
    goods_amount = get_getvalue(request, 'goods_amount')
    try:
        # 根据商品id和商品数量查询商品
        goods = Cart.objects.get(cart_goods_id=goods_id, cart_user_id=get_session(request, 'uid'))
        # 商品存在,更改商品数量------->必须加商品id
        goods.cart_amount = int(goods_amount)
        goods.save()

    except Cart.DoesNotExist:
        # 商品不存在,则添加这个商品
        goods = Cart()
        goods.cart_goods_id = goods_id
        goods.cart_user_id = get_session(request, 'uid')
        goods.cart_amount = goods_amount
        goods.save()
    # 返回json数据
    return JsonResponse({'ret': 1})

# 删除商品
def del_goods(request):
    # 获取商品id
    goods_id = get_getvalue(request, 'goods_id')
    # 删除商品
    try:
        # 商品存在则删除
        goods = Cart.objects.get(cart_goods_id=goods_id, cart_user_id=get_session(request, 'uid'))
        goods.delete()
    except:
        # 不存在则跳过
        pass
    # 返回商品信息
    return JsonResponse({'ret': 1})

goods/views.py
from django.shortcuts import render
from .models import *
from django.core.urlresolvers import reverse
from utils.wrappers import *
# Create your views here.
from .function import *
from django.core.paginator import Paginator

# 首页
@get_total_cart_sum
def index(request):

    # 获取广告信息
    ads1 = Advertise.objects.all()[:4]
    ads2 = Advertise.objects.all()[4:]




    # 获得商品所有分类
    cags = Category.objects.all()

    # 获得每一个分类的最新商品的列表(4个),热门商品(3个)
    for cag in cags:
        # 获得最新商品4个
        new_goods = GoodsInfo.objects.get_new_goods(cag, 4)
        # 获得最热商品3个
        hot_goods = GoodsInfo.objects.get_hot_goods(cag, 3)

        ################为什么有个.hot.new####################
        # print(cag.new)
        cag.new = new_goods
        cag.hot = hot_goods

    return render(request, 'goods/index.html', locals())


# 商品详情
@get_total_cart_sum
def detail(request):

    # 获取get请求id
    key_id = get_getvalue(request, 'id')

    # 获取商品信息
    good_info = GoodsInfo.objects.get(pk=key_id)




    # 获取两个所有商品中最热门的
    good_new = GoodsInfo.objects.get_new_by_all_goods()

    # 更新用户浏览记录
    update_user_browe_record(request)

    return render(request, 'goods/detail.html', locals())


# 商品列表
@get_total_cart_sum
def goods_list(request, cag_id, pag_id):

    #读取商品分类
    cags = Category.objects.all()

    show = get_getvalue(request, 'show')
    print(show)
    #根据商品的id分类获取商品列表
    goods_lists = GoodsInfo.objects.get_goods_by_cagid(cag_id, show)

    # 创建分页对象
    paginator = Paginator(goods_lists, 10)
    # 获得当前分页数据
    current_page = paginator.page(pag_id)

    goods_new = GoodsInfo.objects.get_new_by_all_goods(2)

    pag_id = int(pag_id)

    return render(request, 'goods/list.html', locals())

templates/goods/cart.html
<div class="guest_cart fr">
    <a href="{% url 'carts:cart' %}" class="cart_name fl">我的购物车</a>
    <div class="goods_count fl" id="show_count">{{ request.total }}</div>
</div>

templates/goods/detail.html
{% extends 'common/base.html' %}

{% load staticfiles %}

{% block head_js %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
{#        更新商品总价格#}
        function update_price() {
            num = parseInt($('.num_show').val());
            price = parseInt($('.show_pirze').find('em').html());

            total = num * price;
            $('.total').find('em').html(total+'元');
        }


        $(function () {
            $('.add').click(function () {
{#                # 获取数量#}
                num = $('.num_show').val();
                num = parseInt(num) + 1;
                $('.num_show').val(num);
                update_price();
            });
        });
        $(function () {
            $('.minus').click(function () {
{#                # 获取数量#}
                num = $('.num_show').val();
                num = parseInt(num) - 1;
                if (num <= 0)num = 1;
                $('.num_show').val(num);
                update_price();
            });
        });

        $(function () {
            $('#add_cart').click(function () {
                good_id = $('#goods_id').val();
                good_num = $('.num_show').val();

                $.get('/carts/add_goods/', {'goods_id':good_id, 'goods_num': good_num}, function (total) {
{#                    alert(total['total'])#}
                    $('#show_count').html(total['total'])

                })
            })
        })

    </script>
{% endblock head_js%}


{% block body %}


{% include 'common/status.html' %}


	<div class="search_bar clearfix">
        {% include 'common/logo.html' %}
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
{#            购物车    #}
        {% include 'goods/cart.html' %}
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="/static/{{ good_info.good_image }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ good_info.good_name }}</h3>
			<p>{{ good_info.good_compendium }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ good_info.good_price }}</em></span>
				<span class="show_unit">单  位：{{ good_info.good_unit }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
			<div class="total">总价：<em>{{ good_info.good_price }}元</em></div>
			<div class="operate_btn">
                <input type="hidden" value="{{ good_info.id }}" id="goods_id">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>				
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for good in good_new %}
					<li>
						<a href="{% url 'goods:detail' %}?id={{ good.id }}"><img src="/static/{{ good.good_image }}"></a>
						<h4><a href="{% url 'goods:detail' %}?id={{ good.id }}">{{ good.good_name }}</a></h4>
						<div class="prize">￥{{ good.good_price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ good_info.good_details }}</dd>
				</dl>
			</div>

		</div>
	</div>


    {% block end_js %}
    <div class="add_jump"></div>
	<script type="text/javascript" src="{% static "js/jquery-1.12.2.js" %}"></script>
{#	<script type="text/javascript">#}
{##}
{#		$('#add_cart').click(function(){#}
{##}
{#		    var $add_x = $('#add_cart').offset().top;#}
{#		    var $add_y = $('#add_cart').offset().left;#}
{##}
{#		    var $to_x = $('#show_count').offset().top;#}
{#		    var $to_y = $('#show_count').offset().left;#}
{##}
{#		    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'});#}
{##}
{##}
{#			$(".add_jump").stop().animate({#}
{#				'left': $to_y+7,#}
{#				'top': $to_x+7},#}
{#				"fast", function() {#}
{#					$(".add_jump").fadeOut('fast',function(){#}
{#						$('#show_count').html(2);#}
{#					});#}
{##}
{#			});#}
{#		})#}
{#	</script>#}
    {% endblock end_js %}
{% endblock body %}

templates/goods/index.html
{% extends 'common/base.html' %}

{% load staticfiles %}


{% block head_js %}
    <script type="text/javascript" src="{% static "js/jquery-1.12.4.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery-ui.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/slide.js" %}"></script>
{% endblock head_js %}

{% block body %}
    {% include 'common/status.html' %}

	<div class="search_bar clearfix">
        {% include 'common/logo.html' %}
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
        {#    购物车    #}
        {% include 'goods/cart.html' %}
	</div>

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for ad in ads1 %}
                    <li><img src="/static/{{ ad.ad_image }}" alt="幻灯片"></li>
                {% endfor %}

{#				<li><img src="{% static "images/slide.jpg" %}" alt="幻灯片"></li>#}
{#				<li><img src="{% static "images/slide02.jpg" %}" alt="幻灯片"></li>#}
{#				<li><img src="{% static "images/slide03.jpg" %}" alt="幻灯片"></li>#}
{#				<li><img src="{% static "images/slide04.jpg" %}" alt="幻灯片"></li>#}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
             {% for ad in ads2 %}
			<a href="{{ ad.ad_link }}"><img src="/static/{{ ad.ad_image }}"></a>
            {% endfor %}
{#			<a href="#"><img src="{% static "images/adv02.jpg" %}"></a>#}
		</div>
	</div>

{% for cag in cags %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">{{ cag.cag_name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
{#                显示最热门的三个商品#}
                {% for good in cag.hot %}
				<a href="{% url 'goods:detail' %}?id={{ good.id }}">{{ good.good_name }}</a>
                {% endfor %}
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

    {% load goods_filters %}

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{% static forloop.counter|create_imgage_name  %}"></div>
			<ul class="goods_list fl">
				{% for good in cag.new %}
	                <li>
					    <h4><a href="{% url 'goods:detail' %}?id={{ good.id }}">{{ good.good_name }}</a></h4>
					    <a href="{% url 'goods:detail' %}?id={{ good.id }}"><img src="{% static good.good_image %}"></a>
					    <div class="prize">¥ {{ good.good_price }}</div>
				    </li>
				{% endfor %}
			</ul>
		</div>
	</div>

{% endfor %}

	{% block end_js %}


	<script type="text/javascript" src="{% static "js/slideshow.js" %}"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>

    {% endblock end_js %}
{% endblock body%}

templates/goods/list.html
{% extends 'common/base.html' %}
{# 加载静态文件 #}
{% load staticfiles %}

{% block body %}


    {% include 'common/status.html' %}


	<div class="search_bar clearfix">
        {% include 'common/logo.html' %}
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
        {#    购物车    #}
        {% include 'goods/cart.html' %}
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="{% url 'goods:goods_list' cags.0.id 1 %}" class="fruit">{{ cags.0.cag_name }}</a></li>
					<li><a href="{% url 'goods:goods_list' cags.1.id 1 %}" class="seafood">{{ cags.1.cag_name }}</a></li>
					<li><a href="{% url 'goods:goods_list' cags.2.id 1 %}" class="meet">{{ cags.2.cag_name }}</a></li>
					<li><a href="{% url 'goods:goods_list' cags.3.id 1 %}" class="egg">{{ cags.3.cag_name }}</a></li>
					<li><a href="{% url 'goods:goods_list' cags.4.id 1 %}" class="vegetables">{{ cags.4.cag_name }}</a></li>
					<li><a href="{% url 'goods:goods_list' cags.5.id 1 %}" class="ice">{{ cags.5.cag_name }}</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for good in goods_new %}
					<li>
						<a href='{% url 'goods:detail' %}?id={{ good.id }}'><img src="{% static good.good_image %}"></a>
						<h4><a href="{% url 'goods:detail' %}?id={{ good.id }}">{{ good.good_name }}</a></h4>
						<div class="prize">￥{{ good.good_price }}</div>
					</li>
{##}            {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:goods_list' cag_id 1 %}" {% if not show %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:goods_list' cag_id 1 %}?show=price" {% if show == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:goods_list' cag_id 1 %}?show=hot" {% if show == 'hot'%}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
				{% for good in current_page %}
                <li>
					<a href={% url 'goods:detail' %}?id={{ good.id }}><img src="{% static good.good_image %}"></a>
					<h4><a href={% url 'goods:detail' %}?id={{ good.id }}>{{ good.good_name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ good.good_price }}</span>
						<span class="unit">{{ good.good_price }}/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
{#				<li>#}
{#					<a href="#"><img src="{% static "images/goods/goods004.jpg" %}"></a>#}
{#					<h4><a href="#">吐鲁番梨光杏</a></h4>#}
{#					<div class="operate">#}
{#						<span class="prize">￥5.50</span>#}
{#						<span class="unit">5.50/500g</span>#}
{#						<a href="#" class="add_goods" title="加入购物车"></a>#}
{#					</div>#}
{#				</li>#}
			    </ul>

			<div class="pagenation">
{#           页面编辑#}
                {% if current_page.has_previous %}
                    <a href="{% url 'goods:goods_list' cag_id current_page.previous_page_number %}{% if show %}?show={{ show }}{% endif %}">上一页></a>
                {% endif %}

{#				<a href="#" class="active">1</a>#}
{#				<a href="#">2</a>#}
                {% for index in paginator.page_range %}
                    {% if pag_id == index %}
                        <a href="{% url 'goods:goods_list' cag_id index %}{% if show %}?show={{ show }}{% endif %}" class="active">{{ index }}</a>
                    {% else %}
                        <a href="{% url 'goods:goods_list' cag_id index %}{% if show %}?show={{ show }}{% endif %}" >{{ index }}</a>
                    {% endif %}
                {% endfor %}

                {% if current_page.has_next %}
                <a href="{% url 'goods:goods_list' cag_id current_page.next_page_number %}{% if show %}?show={{ show }}{% endif %}">下一页></a>
                {% endif %}

            </div>
		</div>
	</div>



	
{% endblock body %}