carts/urls.py
from django.conf.urls import url, include
from .views import *

# ^起始字符一定要加,$结束符号根据要求
urlpatterns = [
    url(r'^cart/$', cart, name='cart'),
    url(r'^add_goods/$', add_goods, name='add_goods'),
    url(r'^edit_goods_num/$', edit_goods_num, name='edit_goods_num'),
    url(r'^del_goods/$', del_goods, name='del_goods'),
]

goods/urls.py
from django.conf.urls import url, include
from .views import *

# ^起始字符一定要加,$结束符号根据要求
urlpatterns = [
    url(r'^index/$', index, name='index'),
    url(r'^detail/$', detail, name='detail'),
    url(r'^goods_list/(\d+)/(\d+)/$', goods_list, name='goods_list'),
]

myweb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', ''),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^order/', include('order.urls', namespace='order')),
    #url(r'^favicon.ico$', RedirectView.as_view(url='static/favicon.ico'))
]



#handler404 = 'my_app.views.my_custom_page_not_found_view'
#handler500 = 'my_app.views.my_custom_error_view'
#handler403 = 'my_app.views.my_custom_permission_denied_view'

order/urls.py
from django.conf.urls import url, include
from .views import *

# ^起始字符一定要加,$结束符号根据要求
#
urlpatterns = [
    url(r'^order/', order, name='order'),
    url(r'^balance_order/', balance_order, name='balance_order'),
]

users/urls.py
from django.conf.urls import url
from .views import *

# ^起始字符一定要加,$结束符号根据要求
urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^register/$', register, name='register'),
    url(r'^user_center_info/$', info, name='info'),
    url(r'^user_center_order/$', order, name='order'),
    url(r'^user_center_site/$', site, name='site'),
    # 处理注册信息
    url(r'^deal_register/$', deal_register, name='deal_register'),
    # 处理用户名是否存在
    url(r'^checkname/$', check_name, name='check_name'),
    # 处理登录信息
    url(r'^login_handle/$', login_handle, name='login_handle'),
    # 注销
    url(r'^login_out/$', login_out, name='login_out'),
    # 地址信息修改
    url(r'^info_edit$', info_edit, name='info_edit'),
]

templates/common/base.html
{% load staticfiles %}


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-提交订单</title>
	<link rel="stylesheet" type="text/css" href="{% static "css/reset.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
    {% block head_js %}
        {#  头js文件   #}
    {% endblock head_js %}
</head>
<body>
    {% block body %}
        {#    body内容    #}
    {% endblock body %}



    <div class="footer">
        <div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

    {% block end_js %}
        {#    尾js    #}
    {% endblock end_js %}


</body>
</html>
    

    

templates/common/left_menu.html
{% load users_filters %}

{#		<div class="left_menu_con clearfix">#}
{#			<h3>用户中心</h3>#}
{#			<ul>#}
{#				<li><a href="{% url 'users:info' %}"  {% if flag == 'info' %} class="active" {% endif %} >· 个人信息</a></li>#}
{#				<li><a href="{% url 'users:order' %}" {% if flag == 'order' %} class="active" {% endif %} >· 全部订单</a></li>#}
{#				<li><a href="{% url 'users:site' %}"  {% if flag == 'site' %} class="active" {% endif %} >· 收货地址</a></li>#}
{#			</ul>#}
{#		</div>#}


		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
            {% with menus=flag|create_menu  %}
                {% for menu in menus %}
                    <li><a href="{{ menu.link }}" class="{{ menu.active }}">. {{ menu.name }}</a></li>
                {% endfor %}
            {% endwith %}

            </ul>
		</div>

templates/common/logo.html
{% load staticfiles %}
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static "images/logo.png" %}"></a>

templates/common/status.html
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">

                {% if request.session.username %}
				<div class="login_btn fl">
					欢迎您：<em>{{ request.session.username }}</em>
                    <span>|</span>
					<a href="{% url 'users:login_out' %}">注销</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'users:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'users:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'users:info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'carts:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'users:order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>