carts/urls.py
from django.conf.urls import url, include
from .views import *

# ^起始字符一定要加,$结束符号根据要求
urlpatterns = [
    url(r'^cart/$', cart, name='cart'),
    url(r'^add_goods/$', add_goods, name='add_goods'),
    url(r'^edit_goods_num/$', edit_goods_num, name='edit_goods_num'),
    url(r'^del_goods/$', del_goods, name='del_goods'),
]

goods/urls.py
from django.conf.urls import url, include
from .views import *

# ^起始字符一定要加,$结束符号根据要求
urlpatterns = [
    url(r'^index/$', index, name='index'),
    url(r'^detail/$', detail, name='detail'),
    url(r'^goods_list/(\d+)/(\d+)/$', goods_list, name='goods_list'),
]

myweb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', ''),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^order/', include('order.urls', namespace='order')),
    #url(r'^favicon.ico$', RedirectView.as_view(url='static/favicon.ico'))
]



#handler404 = 'my_app.views.my_custom_page_not_found_view'
#handler500 = 'my_app.views.my_custom_error_view'
#handler403 = 'my_app.views.my_custom_permission_denied_view'

users/urls.py
from django.conf.urls import url
from .views import *

# ^起始字符一定要加,$结束符号根据要求
urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^register/$', register, name='register'),
    url(r'^user_center_info/$', info, name='info'),
    url(r'^user_center_order/$', order, name='order'),
    url(r'^user_center_site/$', site, name='site'),
    # 处理注册信息
    url(r'^deal_register/$', deal_register, name='deal_register'),
    # 处理用户名是否存在
    url(r'^checkname/$', check_name, name='check_name'),
    # 处理登录信息
    url(r'^login_handle/$', login_handle, name='login_handle'),
    # 注销
    url(r'^login_out/$', login_out, name='login_out'),
    # 地址信息修改
    url(r'^info_edit$', info_edit, name='info_edit'),
]

order/models.py
from django.db import models
from db.AbstractModel import AbstractModel

# Create your models here.
# 订单详细信息表
class GoodsDetail(AbstractModel):
    # 商品名称
    detail_name = models.CharField(max_length=50)
    # 商品价格
    detail_price = models.IntegerField()
    # 商品数量
    detail_amount = models.IntegerField()
    # 商品单位
    detail_unit = models.CharField(max_length=10)
    # 商品图片
    detail_image = models.ImageField()
    # 商品id
    detail_goodsID = models.IntegerField()
    # 所属订单
    detail_order = models.ForeignKey('Order')


# 订单信息模型
class Order(AbstractModel):
    status = (
        (1, '待支付'),
        (2, '待发货'),
        (3, '待收货'),
        (4, '已完成'),
    )

    pay = (
        (1, '货到付款'),
        (2, '微信支付'),
        (3, '支付宝支付'),
        (4, '银联支付'),
    )

    # 订单编号
    order_num = models.CharField(max_length=50)
    # 订单收货地址
    order_addr = models.CharField(max_length=50)
    # 收件人姓名
    order_recName = models.CharField(max_length=20)
    # 收件人号码
    order_tele = models.CharField(max_length=12)
    # 运费
    order_fee = models.IntegerField(default=10)
    # 订单状态
    order_status = models.SmallIntegerField(choices=status, default=1)
    #　订单支付方式
    order_pay = models.SmallIntegerField(choices=pay, default=1)
    # 订单所属用户
    order_user = models.ForeignKey('users.User')




'''
# 自定义管理器模式
class 自定义管理器类名(models.Manager):
    # 管理器新增方法
    def 方法名(self):
        # 获取父类方法
        变量 = super(自定义管理器类名, self).all()
        """""""
        # 处理过程
        """"""" 
        return 变量
'''
'''
# 字段元选项
class Meta:
        # 重定义数据库的数据表名
        db_table = 'my_custom_dbname'
        # 表示该模型类为抽象类,不生成表
        abstract = True
        # 排序
        ordering = ['-id']
'''

users/models.py
from django.db import models
from db.AbstractModel import *
# Create your models here.
from utils.wrappers import *
class UserManager(models.Manager):
    # 通过国用户名获取用户数据
    def get_userData_by_name(self, username):
        try:
            return self.get(user_name=username)
        except User.DoesNotExist:
            return None

    # 用户注册数据保存
    def user_registerData_save(self, request):
        userinfo = self.model()
        userinfo.user_name = post_getvalue(request, 'user_name')
        userinfo.user_pass = password_encryption(post_getvalue(request, 'user_pwd1'))
        userinfo.user_mail = post_getvalue(request, 'user_email')
        # print(type(userinfo.user_mail))
        # print(type(userinfo.user_pass))

        userinfo.save()


    # 用户地址信息保存
    def user_addrInfo_save(self, request):
        useraddrInfo = self.get_userData_by_name(get_session(request, 'username'))
        useraddrInfo.user_recv = post_getvalue(request, 'user_recv')
        useraddrInfo.user_addr = post_getvalue(request, 'user_site')
        useraddrInfo.user_code = post_getvalue(request, 'user_group')
        useraddrInfo.user_tele = post_getvalue(request, 'user_tele')
        useraddrInfo.save()


# 用户模型类
class User(AbstractModel):

    # 用户名
    user_name = models.CharField(max_length=20)
    # 用户密码
    user_pass = models.CharField(max_length=100)
    # 用户邮箱
    user_mail = models.CharField(max_length=50)
    # 用户地址
    user_addr = models.CharField(max_length=50)
    # 用户手机
    user_tele = models.CharField(max_length=11)
    # 邮政编码
    user_code = models.CharField(max_length=10)
    # 收件人
    user_recv = models.CharField(max_length=10, default='')


   # 创建自定义管理器类
    objects = UserManager()


# 用户浏览记录模型
class RecordBrowse(AbstractModel):
    # 浏览商品
    browse_good = models.ForeignKey('goods.GoodsInfo')
    # 浏览者
    browse_user = models.ForeignKey('User')








'''
# 自定义管理器模式
class 自定义管理器类名(models.Manager):
    # 管理器新增方法
    def 方法名(self):
        # 获取父类方法
        变量 = super(自定义管理器类名, self).all()
        """""""
        # 处理过程
        """"""" 
        return 变量
'''
'''
# 字段元选项
class Meta:
        # 重定义数据库的数据表名
        db_table = 'my_custom_dbname'
        # 表示该模型类为抽象类,不生成表
        abstract = True
        # 排序
        ordering = ['-id']
'''

users/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse, JsonResponse
from .functions import *
from .models import *
from goods.function import  *
from order.models import *
# Create your views here.
from django.core.paginator import Paginator


def login(request):
    # 判断是否记录账号
    if get_cookies(request, 'memb_acount'):
        memb_acount = get_cookies(request, 'memb_acount')

    return render(request, 'users/login.html', locals())


def register(request):
    error_mess = get_message(request)

    return render(request, 'users/register.html', locals())


# 用户中心-个人信息
@check_permission
def info(request):
    # 获取用户信息
    user = User.objects.get_userData_by_name(get_session(request, 'username'))
    # 获取关联的信息
    records = user.recordbrowse_set.all().order_by('-update_time')

    return render(request, 'users/user_center_info.html', locals())


# 用户中心-订单中心
@check_permission
def order(request):
    # 获取用户id
    user_id = get_session(request, 'uid')
    # 查询该用户全部订单信息,需要按时间逆序,最后的订单在前
    orders = Order.objects.filter(order_user_id=user_id).order_by('-update_time')

    # 设置一个分页面
    paginator = Paginator(orders, 2)
    # 获取当前页码
    current_page = get_getvalue(request, 'page')
    if not current_page:
        current_page = 1
    # 从当前页获取数据
    orders = paginator.page(current_page)

    # 查询订单
    for order in orders:
        # 绑定一个订单总价
        order.total_money = 0
        # 遍历订单中的商品,求出总价,在模板中直接使用order.goodsdetail_set.all
        for goods in order.goodsdetail_set.all():
            order.total_money += goods.detail_amount * goods.detail_price

    return render(request, 'users/user_center_order.html', locals())


# 用户中心 -收货地址
@check_permission
def site(request):
    # 获取个人信息
    user_addrInfo = User.objects.get_userData_by_name(get_session(request, 'username'))

    return render(request, 'users/user_center_site.html', locals())


# 处理注册信息
def deal_register(request):
    #　判断资料是否符合情况
    if check_register_param(request):
        # 符合情况,加入数据库
        User.objects.user_registerData_save(request)
        print('注册成功')
        return redirect(reverse('users:login'))
    else:
        # 不符合情况,跳转回注册界面
        print('注册不成功')
        return redirect(reverse('users:register'))


#
def check_name(request):
    # 获取request中的username
    user_name = get_getvalue(request, 'username')
    # 获取数据是否存在该name
    bool_name = is_name_existing(user_name)

    if bool_name:
        # 用户名存在
        bool_name = True
    else:
        # 用户名不存在
        bool_name = False

    return JsonResponse({'ret': bool_name})


def login_handle(request):
    # 获取账号和密码
    username_login = post_getvalue(request, 'username_login')
    password_login = post_getvalue(request, 'password_login')
    member_account = post_getvalue(request, 'member_account')
    # 从数据库中效验信息,返回账号和密码
    password = get_name_and_passwd(username_login)

    # 密码匹配
    if password == password_encryption(password_login):
        # 定义response
        response = redirect(reverse('goods:index'))
        # 记录用户登录状态,写session
        keep_login_online(request, username_login)

        # # 判断是否有登录前的页面
        # url = get_session(request, 'pre_url')
        # print('prev_url------>', url)
        # if url:
        #     response = redirect(url)

        # 确定是否要记录账号
        if member_account:
            set_cookies(response, 'memb_acount', username_login)
        # 返回response,即连接index
        return response
    # 密码不匹配
    else:
        return redirect(reverse('users:login'))

# 注销
def login_out(request):
    # 消除session
    del_session(request)
    # 返回登录界面
    return redirect(reverse('users:login'))


# 处理地址信息修改
def info_edit(request):
    # 地址效验
    if check_addr_info(request):
        # 保存信息
        User.objects.user_addrInfo_save(request)

    return redirect(reverse('users:info'))

templates/users/login.html
{% extends 'common/base.html' %}
{# 加载静态文件 #}
{% load staticfiles %}

{% block body %}

	<div class="login_top clearfix">
		<a href="../goods/index.html" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'users:register' %}">立即注册</a>
				</div>
				<div class="form_input">

					<form action="{% url 'users:login_handle' %}" method="post">
                        {% csrf_token %}
						<input type="text" name="username_login" class="name_input" placeholder="请输入用户名" value={{ memb_acount }}>
						<div class="user_error">输入错误</div>
						<input type="password" name="password_login" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="member_account">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

templates/users/register.html
{% extends 'common/base.html' %}

{% load staticfiles %}

{% block head_js %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock head_js %}

{% block body %}

	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static "images/logo02.png" %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'users:login' %}">登录</a>
			</div>

			<div class="reg_form clearfix">
				<form id="reg_form" action="{% url 'users:deal_register' %}" method="post">
				<ul>
                    {% csrf_token %}
					<li>
                        <label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
                        <span class="error_tip_info">{{ error_mess.user_name }}</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="user_pwd1" id="user_pwd1">
						<span class="error_tip">提示信息</span>
                        <span class="error_tip_info">{{ error_mess.user_pwd1 }}</span>

					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="user_pwd2" id="user_pwd2">
						<span class="error_tip">提示信息</span>
                        <span class="error_tip_info">{{ error_mess.user_pwd2 }}</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="user_email" id="user_email">
						<span class="error_tip">提示信息</span>
                        <span class="error_tip_info">{{ error_mess.user_email }}</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="user_allow" id="user_allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
                        <span class="error_tip_info">{{ error_mess.user_allow }}</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>

{% endblock body %}

templates/users/user_center_info.html
{% extends 'common/base.html' %}
{% load staticfiles %}


{% block body %}

    {% include 'common/status.html' %}


	<div class="search_bar clearfix">
        {% include 'common/logo.html' %}
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
        {% include 'common/left_menu.html' with flag='info' %}
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>收件人：</span>{{ user.user_recv|default:'未填写' }}</li>
							<li><span>联系方式：</span>{{ user.user_tele|default:'未填写' }}</li>
							<li><span>联系地址：</span>{{ user.user_addr|default:'未填写' }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">



{#				<li>#}
{#					<a href="#"><img src="{% static "images/goods/goods006.jpg" %}"></a>#}
{#					<h4><a href="#">进口西梅</a></h4>#}
{#					<div class="operate">#}
{#						<span class="prize">￥28.80</span>#}
{#						<span class="unit">28.8/500g</span>#}
{#						<a href="#" class="add_goods" title="加入购物车"></a>#}
{#					</div>#}
{#				</li>#}

                {% for record in records %}
				<li>
					<a href="{% url 'goods:detail' %}?id={{ record.browse_good.id }}"><img src="{%  static  record.browse_good.good_image %} "></a>
					<h4><a href="{% url 'goods:detail' %}?id={{ record.browse_good.id }}">{{ record.browse_good.good_name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ record.browse_good.good_price }}</span>
						<span class="unit">{{ record.browse_good.good_price }}/{{ record.browse_good.good_unit }}g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}

			</ul>
		</div>
		</div>
	</div>

{% endblock body %}

templates/users/user_center_order.html
{% extends 'common/base.html' %}
{% load staticfiles %}

{% block head_js %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        $(function () {
            $('.order_goods_list').each(function () {
                amount =  parseInt($(this).find('.col03').html());
                price = parseFloat($(this).find('.col04').html());
                money = amount * price;
                $(this).find('.col04').html(money + '元');
            })
        })

    </script>

{% endblock head_js %}

{% block body %}

{% include 'common/status.html' %}


	<div class="search_bar clearfix">
 {% include 'common/logo.html' %}
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>

	<div class="main_con clearfix">
        {% include 'common/left_menu.html' with flag='order' %}
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>

                {% for order in orders %}
                    <ul class="order_list_th w978 clearfix">
                        <li class="col01">{{ order.update_time }}</li>
                        <li class="col02">订单号：{{ order.order_num }}</li>
                        <li class="col02 stress">
                            {% if order.order_status == 1 %}
                                未支付
                            {% elif order.order_status == 2 %}
                                待发货
                            {% elif order.order_status == 3 %}
                                待收货
                            {% elif order.order_status == 4 %}
                                已完成
                            {% endif %}
                        </li>
                    </ul>

                    <table class="order_list_table w980">
                        <tbody>
                            <tr>
                                <td width="55%">
                                    {% for goods in order.goodsdetail_set.all %}
                                        <ul class="order_goods_list clearfix">
                                            <li class="col01"><img src="{% static goods.detail_image %}"></li>
                                            <li class="col02">{{ goods.detail_name }}<em>{{ goods.detail_price }}元/{{ goods.detail_unit }}</em></li>
                                            <li class="col03">{{ goods.detail_amount }}</li>
                                            <li class="col04">{{ goods.detail_price }}</li>
                                        </ul>
                                    {% endfor %}

                                </td>
                                <td width="15%">{{ order.total_money }}元</td>
                                <td width="15%">
                                    {% if order.order_status == 1 %}
                                        未支付
                                    {% elif order.order_status == 2 %}
                                        待发货
                                    {% elif order.order_status == 3 %}
                                        待收货
                                    {% elif order.order_status == 4 %}
                                        已完成
                                    {% endif %}
                                </td>
                                <td width="15%"><a href="#" class="oper_btn">去付款</a></td>
                            </tr>
                        </tbody>
                    </table>
				 {% endfor %}

				<div class="pagenation">
                    {% if paginator.page.has_previous %}
					    <a href="{% url 'users:order' %}?page={{ paginator.page.previous_page_number }}">上一页</a>
                    {% endif %}

                    {% for index in paginator.page_range %}
                        <a href="{% url 'users:order' %}?page={{ index }}" {% if paginator.page == index %} class="active" {% endif %}>{{ index }}</a>
                    {% endfor %}

                    {% if paginator.page.has_next %}
					<a href="{% url 'users:order' %}?page={{ paginator.page.next_page_number }}">下一页></a>
                    {% endif %}
				</div>
		</div>
	</div>

{% endblock body %}

templates/users/user_center_site.html
{% extends 'common/base.html' %}
{% load staticfiles %}
{% block body %}

    {% include 'common/status.html' %}

	<div class="search_bar clearfix">
        {% include 'common/logo.html' %}
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>

	<div class="main_con clearfix">
            {% include 'common/left_menu.html' with flag='site' %}
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ user_addrInfo.user_addr }} （{{ user_addrInfo.user_recv }} 收） {{ user_addrInfo.user_tele }}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post" action="{% url 'users:info_edit' %}">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="user_recv" value="{{ user_addrInfo.user_recv }}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="user_site" >{{ user_addrInfo.user_addr }}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="user_group"  value="{{ user_addrInfo.user_code }}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="user_tele" value="{{ user_addrInfo.user_tele }}">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>

{% endblock body %}