carts/urls.py
from django.conf.urls import url, include
from .views import *

# ^起始字符一定要加,$结束符号根据要求
urlpatterns = [
    url(r'^cart/$', cart, name='cart'),
    url(r'^add_goods/$', add_goods, name='add_goods'),
    url(r'^edit_goods_num/$', edit_goods_num, name='edit_goods_num'),
    url(r'^del_goods/$', del_goods, name='del_goods'),
]

myweb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', ''),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^order/', include('order.urls', namespace='order')),
    #url(r'^favicon.ico$', RedirectView.as_view(url='static/favicon.ico'))
]



#handler404 = 'my_app.views.my_custom_page_not_found_view'
#handler500 = 'my_app.views.my_custom_error_view'
#handler403 = 'my_app.views.my_custom_permission_denied_view'

order/urls.py
from django.conf.urls import url, include
from .views import *

# ^起始字符一定要加,$结束符号根据要求
#
urlpatterns = [
    url(r'^order/', order, name='order'),
    url(r'^balance_order/', balance_order, name='balance_order'),
]

users/urls.py
from django.conf.urls import url
from .views import *

# ^起始字符一定要加,$结束符号根据要求
urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^register/$', register, name='register'),
    url(r'^user_center_info/$', info, name='info'),
    url(r'^user_center_order/$', order, name='order'),
    url(r'^user_center_site/$', site, name='site'),
    # 处理注册信息
    url(r'^deal_register/$', deal_register, name='deal_register'),
    # 处理用户名是否存在
    url(r'^checkname/$', check_name, name='check_name'),
    # 处理登录信息
    url(r'^login_handle/$', login_handle, name='login_handle'),
    # 注销
    url(r'^login_out/$', login_out, name='login_out'),
    # 地址信息修改
    url(r'^info_edit$', info_edit, name='info_edit'),
]

order/models.py
from django.db import models
from db.AbstractModel import AbstractModel

# Create your models here.
# 订单详细信息表
class GoodsDetail(AbstractModel):
    # 商品名称
    detail_name = models.CharField(max_length=50)
    # 商品价格
    detail_price = models.IntegerField()
    # 商品数量
    detail_amount = models.IntegerField()
    # 商品单位
    detail_unit = models.CharField(max_length=10)
    # 商品图片
    detail_image = models.ImageField()
    # 商品id
    detail_goodsID = models.IntegerField()
    # 所属订单
    detail_order = models.ForeignKey('Order')


# 订单信息模型
class Order(AbstractModel):
    status = (
        (1, '待支付'),
        (2, '待发货'),
        (3, '待收货'),
        (4, '已完成'),
    )

    pay = (
        (1, '货到付款'),
        (2, '微信支付'),
        (3, '支付宝支付'),
        (4, '银联支付'),
    )

    # 订单编号
    order_num = models.CharField(max_length=50)
    # 订单收货地址
    order_addr = models.CharField(max_length=50)
    # 收件人姓名
    order_recName = models.CharField(max_length=20)
    # 收件人号码
    order_tele = models.CharField(max_length=12)
    # 运费
    order_fee = models.IntegerField(default=10)
    # 订单状态
    order_status = models.SmallIntegerField(choices=status, default=1)
    #　订单支付方式
    order_pay = models.SmallIntegerField(choices=pay, default=1)
    # 订单所属用户
    order_user = models.ForeignKey('users.User')




'''
# 自定义管理器模式
class 自定义管理器类名(models.Manager):
    # 管理器新增方法
    def 方法名(self):
        # 获取父类方法
        变量 = super(自定义管理器类名, self).all()
        """""""
        # 处理过程
        """"""" 
        return 变量
'''
'''
# 字段元选项
class Meta:
        # 重定义数据库的数据表名
        db_table = 'my_custom_dbname'
        # 表示该模型类为抽象类,不生成表
        abstract = True
        # 排序
        ordering = ['-id']
'''

order/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from utils.wrappers import *
from carts.models import *
from .models import *
from goods.models import *
from users.models import User
from django.http import JsonResponse
import time
from django.db import transaction
# Create your views here.


# 提交订单
def order(request):
    # 结算的商品编号
    goods_id_list = post_getlist(request, 'goods_id')

    # 结算的商品
    cart_goods = Cart.objects.filter(cart_user_id=get_session(request, 'uid'), cart_goods_id__in=goods_id_list)

    total_num = 0
    total_money = 0
    for goods in cart_goods:

        # 单个商品总价
        goods.single_total_money = goods.cart_amount * goods.cart_goods.good_price
        # 商品总数
        total_num += goods.cart_amount
        # 商品总数,商品总价
        total_money += goods.single_total_money

        cart_goods.total_num = total_num
        cart_goods.total_money = total_money

        cart_goods.total_money_and_freight = cart_goods.total_money + 10

        user = User.objects.get(id=get_session(request, 'uid'))

    goods_id_list = ','.join(goods_id_list)

    return render(request, 'order/place_order.html', locals())


@transaction.atomic()
def balance_order(request):
    # 获取商品,根据获取的字符串生成商品id列表
    goods_idList = post_getvalue(request, 'idList').split(',')
    # 获取购买方式
    pay_way = post_getvalue(request, 'pay_way')
    # 获取购买用户id
    user_id = int(get_session(request, 'uid'))
    # 获取用户信息,通过order_user外键获取
    user = User.objects.get(pk=user_id)

    # 创建事务还原点(用于回滚)
    save_point = transaction.savepoint()

    try:
        # 生成订单信息
        orderInfo = Order()
        orderInfo.order_num = str(user_id) + str(int(time.time() * 10000))
        orderInfo.order_user_id = user_id
        orderInfo.order_addr = user.user_addr
        orderInfo.order_recName = user.user_name
        orderInfo.order_tele = user.user_tele
        orderInfo.order_fee = 10
        orderInfo.order_pay = int(pay_way)
        orderInfo.save()

        # 查询已购买商品,根据用户id和商品id
        goods = Cart.objects.filter(cart_user_id=user_id, cart_goods_id__in=goods_idList)

        # 生成订单商品信息
        for good in goods:
            goods_detail = GoodsDetail()
            goods_detail.detail_name = good.cart_goods.good_name
            goods_detail.detail_price = good.cart_goods.good_price
            goods_detail.detail_amount = good.cart_amount
            goods_detail.detail_unit = good.cart_goods.good_unit
            goods_detail.detail_image = good.cart_goods.good_image
            goods_detail.detail_goodsID = good.cart_goods.id
            goods_detail.detail_order = orderInfo
            goods_detail.save()
    except Exception as error:
        # 回滚事务
        transaction.rollback(save_point)
        return JsonResponse({'ret': 0})
    else:
        # 删除购物车
        goods.delete()
        return JsonResponse({'ret': 1})

templates/order/place_order.html
{% extends 'common/base.html' %}
{% load staticfiles %}

{% block head_js %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        $(function () {
            goods_idList = $('#order_btn').attr('good_list');
            csrf_value = $('input[name="csrfmiddlewaretoken"]').val();

            $('.order_submit').click(function () {
                // 必须在点击后进行判断
                pay_way = $('input[name="pay_style"]:checked').val();
                $.post('{% url 'order:balance_order' %}',
                        {'idList': goods_idList, 'csrfmiddlewaretoken':csrf_value, 'pay_way':pay_way},
                        function (data) {
                            if(data['ret'])
                                window.location.href='{% url 'users:order' %}';
                        })
            })
        })

    </script>

{% endblock head_js %}

{% block body %}

    {% include 'common/status.html' %}


	<div class="search_bar clearfix">
        {% include 'common/logo.html' %}
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;提交订单</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>
	
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			<dd><input type="radio" name="" checked="">{{ user.user_recv }} （{{ user.user_name }} 收） {{ user.user_tele }}</dd>
		</dl>
        {# target的作用就是如何打开一个新的连接,该连接为新标签中打开 #}
		<a target="_blank" href="{% url 'users:site' %}" class="edit_site">编辑收货地址</a>

	</div>
	{% csrf_token %}
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" value="1" name="pay_style" checked>
			<label class="cash">货到付款</label>
			<input type="radio" value="2" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" value="3" name="pay_style">
			<label class="zhifubao"></label>
			<input type="radio" value="4" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>

        {% for goods in cart_goods %}
		<ul class="goods_list_td clearfix">
			<li class="col01">{{ forloop.counter }}</li>
			<li class="col02"><img src="{% static goods.cart_goods.good_image %}"></li>
			<li class="col03">{{ goods.cart_goods.good_name }}</li>
			<li class="col04">{{ goods.cart_goods.good_unit }}</li>
			<li class="col05">{{ goods.cart_goods.good_price }}元</li>
			<li class="col06">{{ goods.cart_amount }}</li>
			<li class="col07">{{ goods.single_total_money }}元</li>
		</ul>
        {% endfor %}


	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ cart_goods.total_num }}</em>件商品，总金额<b>{{ cart_goods.total_money }}元</b></div>
			<div class="transit">运费：<b>10元</b></div>
			<div class="total_pay">实付款：<b>{{ cart_goods.total_money_and_freight }}元</b></div>
		</div>
	</div>

    {% csrf_token %}

	<div class="order_submit clearfix">
		<a href="javascript:;" good_list='{{ goods_id_list }}' id="order_btn">提交订单</a>
	</div>	


    {% block end_js %}
	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		
		<div class="mask"></div>
	</div>
	<script type="text/javascript" src="{% static "js/jquery-1.12.2.js" %}"></script>
	<script type="text/javascript">
		$('#order_btn').click(function() {
			localStorage.setItem('order_finish',2);

			$('.popup_con').fadeIn('fast', function() {

				setTimeout(function(){
					$('.popup_con').fadeOut('fast',function(){
						window.location.href = '{% url 'users:order' %}';
					});	
				},3000)
			});
		});
	</script>
    {% endblock end_js %}

{% endblock body %}